# Generated by Django 4.1.5 on 2023-02-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifapp', '0002_imagemodel_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
